#!/bin/bash

BASEDIR="$(dirname "${BASH_SOURCE[0]}")"

bash $BASEDIR/optimize-svgs.sh

find_files() {
	find $BASEDIR -type f \( -name "*.svg" -or -name "*.png" \) | sort | xargs -L 1 realpath --relative-to $BASEDIR
}

extract_extension() {
	echo $(basename $1 | cut -d"." -f2)
}

filename_to_snakecase() {
	echo $(basename $1 | cut -d"." -f1 | tr "-" "_")
}

snakecase_to_pascalcase() {
	text=""
	for arg in $(echo $* | tr "_" "\n"); do
		text=$text"${arg^}"
	done
	echo $text
}

text=""

text=$text"// @NOTE: This file is automatically generated by running 'reindex.sh'.\n"
text=$text"// Please do not modify this file directly, as the changes will most\n"
text=$text"// likely be lost. Instead, the script itself should be modified.\n"

for img in $(find_files); do
	bn=$(filename_to_snakecase $img)
	cn=$(snakecase_to_pascalcase $bn)
	text=$text"export { default as $bn } from \"./$img\";\n"
	if [ "$(extract_extension $img)" == "svg" ]; then
		text=$text"export { ReactComponent as $cn } from \"./$img\";\n"
	else
		text=$text"// @TODO: Maybe there should be an svg version of $(basename $img)?\n"
	fi
done
echo -e "$text" > $BASEDIR/index.ts
